// AUTOGENERATED BY setup.py! DO NOT EDIT MANUALLY!
// By Tyler Clarke.
// This software is protected by GPLv3. That means you have to provide the source for anything that uses my code, and you have to give me credit.
// You can make money off this if you want, but that would be dumb.

// This is the declaration file for the incoming protocol.

#pragma once
#include <util/protocol/protocol.hpp>
namespace protocol::incoming {
struct Init : ProtocolFrameBase {
uint32_t number;
Init(char* data);
void load(char* buffer);
size_t getSize();
};
}
