// AUTOGENERATED BY setup.py! DO NOT EDIT MANUALLY!
// By Tyler Clarke.
// This software is protected by GPLv3. That means you have to provide the source for anything that uses my code, and you have to give me credit.
// You can make money off this if you want, but that would be dumb.

// This is the definition file for the incoming protocol.

#include <util/protocol/incoming.hpp>
protocol::incoming::Init::Init(char* data) {
void protocol::incoming::Init::load(char* buffer) {
buffer[0] = 0;
buffer ++; // clever C hack: rather than worrying about current index, we can just consume a byte of the buffer.
// This is very fast and makes life a lot easier.
for (uint8_t i = 0; i < sizeof(uint32_t); i ++){buffer[i] = ((char*)&number)[i];}
buffer += sizeof(uint32_t); // see above
}

size_t protocol::incoming::Init::getSize() {
return 1 + sizeof(uint32_t);
}
