// AUTOGENERATED BY setup.py! DO NOT EDIT MANUALLY!
// By Tyler Clarke.
// This software is protected by GPLv3. That means you have to provide the source for anything that uses my code, and you have to give me credit.
// You can make money off this if you want, but that would be dumb.

// This is the declaration file for the outgoing protocol.

#pragma once
#include <util/protocol/protocol.hpp>
namespace protocol::outgoing {
struct TestFrame : ProtocolFrameBase {
uint32_t number;
uint32_t numbertwo;
int32_t signedint;
std::string letterz;
float32_t floating;
TestFrame(const char* data);
TestFrame();
void load(char* buffer);
size_t getSize();
};
struct TestFrame2 : ProtocolFrameBase {
std::string text;
float32_t number;
TestFrame2(const char* data);
TestFrame2();
void load(char* buffer);
size_t getSize();
};
}
