// AUTOGENERATED BY setup.py! DO NOT EDIT MANUALLY!
// By Tyler Clarke.
// This software is protected by GPLv3. That means you have to provide the source for anything that uses my code, and you have to give me credit.
// You can make money off this if you want, but that would be dumb.

// This is the declaration file for the outgoing protocol.

#pragma once
#include <util/protocol/protocol.hpp>
namespace protocol::outgoing {
struct TestFrame : ProtocolFrameBase {
uint64_t number;
uint64_t numbertwo;
int64_t signedint;
void load(char* buffer);
size_t getSize();
};
}
