# By Tyler Clarke
# Builds C++ protocol frame definitions and source from manifest.json.
import json

def disclaim(file):
    file.write("""// AUTOGENERATED BY setup.py! DO NOT EDIT MANUALLY!
// By Tyler Clarke.
// This software is protected by GPLv3. That means you have to provide the source for anything that uses my code, and you have to give me credit.
// You can make money off this if you want, but that would be dumb.
""")

def argAdd(file, argument):
    if argument["packing"] == "static": # static packing is very simple. It doesn't require any extra logic; sizeof(type) is sufficient to write it into a buffer.
        # this is the standard packing style for all numbers.
        file.write(argument["type"] + " " + argument["name"] + ";\n")

def argSize(argument):
    if argument["packing"] == "static":
        return "sizeof(" + argument["type"] + ")"

## TODO: convert to little-endian! I don't even know why we're using BE. screw it.
manifest = json.loads(open("manifest.json").read())
for key in manifest.keys():
    header = open(key + ".hpp", "w+")
    source = open(key + ".cpp", "w+")
    disclaim(header)
    header.write("\n// This is the declaration file for the " + key + " protocol.\n\n")
    disclaim(source)
    source.write("\n// This is the definition file for the " + key + " protocol.\n\n#include <util/protocol/" + key + ".hpp>\n")
    header.write("#pragma once\n#include <util/protocol/protocol.hpp>\nnamespace protocol::" + key + " {\n")
    for form in manifest[key]["formats"]:
        header.write("struct " + form["className"] + " : ProtocolFrameBase {\n")
        for argument in form["arguments"]:
            argAdd(header, argument)
        header.write("void load(char* buffer);\nsize_t getSize();\n")
        header.write("};\n")
        source.write("void protocol::" + key + "::" + form["className"] + "::load(char* buffer) {\n")
        source.write("buffer[0] = " + str(form["opcode"]) + ";\nbuffer ++; // clever C hack: rather than worrying about current index, we can just consume a byte of the buffer.\n// This is very fast and makes life a lot easier.\n")
        for argument in form["arguments"]:
            if argument["packing"] == "static":
                source.write("buffer[0] = " + argument["type"] + "_TCHAR;\nbuffer++;")
                source.write("for (uint8_t i = 0; i < sizeof(" + argument["type"] + "); i ++){buffer[i] = ((char*)&" + argument["name"] + ")[i];}\n")
                source.write("buffer += sizeof(" + argument["type"] + "); // see above\n")
        source.write("}\n\n")
        source.write("size_t protocol::" + key + "::" + form["className"] + "::getSize() {\nreturn ")
        source.write(str(len(form["arguments"]) + 1)) ## type bytes and the opcode byte
        for argument in form["arguments"]:
            source.write(" + ")
            source.write(argSize(argument))
        source.write(";\n}\n")
    header.write("}\n")